### ISSUE TITLE
BUG - You cant edit serialized fields in inspector when having one SerializedCallback

### ISSUE THREAD

**Issue by Horothenic** [Siccity/SerializableCallback#21]
I have the following elements elements in my inspector but I cant edit them, I had to remove the serialized callback, assign the things and then add it because I cant edit them anymore.

![image](https://user-images.githubusercontent.com/16009004/90932546-8acce380-e3c4-11ea-86eb-4cf469f5945e.png)
![image](https://user-images.githubusercontent.com/16009004/90932600-ac2dcf80-e3c4-11ea-980c-42595a20b7b1.png)
![image](https://user-images.githubusercontent.com/16009004/90932609-b18b1a00-e3c4-11ea-8e08-eea578276ff4.png)

**Comment by medvedya** [comment]
I have the same one. I commented 27 line "property.serializedObject.Update();" in "SerializableCallbackDrawer", now it seems to work properly.

**Comment by Siccity** [comment]
Are you getting any errors in console?

**Comment by medvedya** [comment]
> Are you getting any errors in console?

There are no errors after or before commenting 27 line.

**Comment by LinusMC** [comment]
I found the problem and fixed it.
All the serialized fields above of SerializedCallback will not be applied.
It caused by the Editor doesn't apply modified properties.

You can add the script "property.serializedObject.ApplyModifiedProperties();" on  the first line of  OnGUI in SerializableCallbackDrawer.
